// ESLint flat config for Treaty-Lab (Next.js 16 + TypeScript).
// Pattern from node_modules/next/dist/docs/01-app/03-api-reference/05-config/03-eslint.md
// (next/typescript + core-web-vitals + prettier compat).
import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier/flat";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  prettier,
  globalIgnores([
    // Next.js defaults
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by Prisma — never hand-edit
    "src/generated/**",
    // SQL migrations
    "prisma/migrations/**",
    // Other build/runtime artifacts
    "node_modules/**",
    ".work/**",
    "public/**",
  ]),
]);

export default eslintConfig;
